arrowParens: always
bracketSameLine: false
bracketSpacing: true
jsxSingleQuote: false
singleQuote: true
trailingComma: all

plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrder:
  - '^~\/'
  - '^\.'
importOrderSeparation: true
importOrderSideEffects: false
importOrderSortSpecifiers: true
importOrderCaseInsensitive: true
