---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/version: ${RELEASE}
    app.kubernetes.io/component: http
    app.kubernetes.io/part-of: ashesdb
    app.kubernetes.io/managed-by: github-actions
data:
  NODE_ENV: production


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/version: ${RELEASE}
    app.kubernetes.io/component: http
    app.kubernetes.io/part-of: ashesdb
    app.kubernetes.io/managed-by: github-actions
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
        app.kubernetes.io/version: ${RELEASE}
        app.kubernetes.io/component: http
        app.kubernetes.io/part-of: ashesdb
        app.kubernetes.io/managed-by: github-actions
    spec:
      imagePullSecrets:
        - name: ghcr.io
      containers:
        - name: app
          image: ghcr.io/ashesdb/app:${RELEASE}
          ports:
            - name: http
              containerPort: 4700
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app
