name: CI

on:
  push:
    branches:
      - master

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('yarn.lock') }}
      - uses: actions/setup-node@v2
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        with:
          node-version: 14
          cache: yarn
      - run: yarn
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

  changed:
    name: Get changed packages
    runs-on: ubuntu-latest
    needs:
      - install
    outputs:
      matrices: ${{ steps.matrices.outputs.matrices }}
      packages: ${{ steps.packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Get changed packages
        id: packages
        run: echo "::set-output name=packages ::$((yarn lerna changed --loglevel silent || true) | paste -sd, -)"
      - name: Generate matrices of jobs for changed packages
        id: matrices
        run: echo "::set-output name=matrices ::$(./.github/scripts/changed-matrices ${{ steps.packages.outputs.packages }})"

  build:
    name: Build packages
    runs-on: ubuntu-latest
    needs:
      - install
      - changed
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Version packages
        run: yarn lerna version --no-git-tag-version --no-push
      - name: Build changed packages
        env:
          CHANGED: ${{ needs.changed.outputs.packages }}
        run: test -z "$CHANGED" || yarn build --scope="{,$CHANGED}" --include-dependencies
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |-
            packages/*/dist
            packages/*/package.json

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Run tests with coverage
        run: yarn test --coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/lcov-report
