name: CI

on:
  push:
    branches:
      - master

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('yarn.lock') }}
      - uses: actions/setup-node@v2
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        with:
          node-version: 14
          cache: yarn
      - run: yarn
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Run tests with coverage
        run: yarn test --coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/lcov-report
